@baseUrl = http://localhost:8080
@api = posts
@id = 61343bf1fd69b0002fed3cee

### @name getAll
GET {{baseUrl}}/{{api}}

### @name getByID
GET {{baseUrl}}/{{api}}/{{id}}

### @name createNew
POST {{baseUrl}}/{{api}}
Content-Type: application/json

{
    "title": "Bài đăng mới 5",
    "content": "Bài đăng không có nội dung 5",
    "time": 123
}

### @name deleteByID
DELETE {{baseUrl}}/{{api}}/{{id}}

### @name updateByID
PUT {{baseUrl}}/{{api}}/{{id}}
Content-Type: application/json

{
    "time": 999
}